---
- name: "change ospf route"
  hosts: junos
  gather_facts: false

  tasks:
    # - name: "set fact"
    #   ansible.builtin.set_fact:
    #     operation: "{{ bypass_or_back }}"
    #   run_once: true

    - name: "set fact"
      ansible.builtin.set_fact:
        operation: "bypass"
      run_once: true

    - name: "get before route"
      import_role: 
        name: show_route
      vars:
        before_or_after: before
      when: inventory_hostname in ['VMX01','VMX02']

    - name: "change ospf metric"
      junipernetworks.junos.junos_config:
        src: "{{ playbook_dir }}/device/{{ inventory_hostname }}/config"
      when: inventory_hostname in ['VMX01','VMX02']

    - name: "get after route"
      import_role: 
        name: show_route
      vars:
        before_or_after: after
      when: inventory_hostname in ['VMX01','VMX02']
