---
- name: "change ospf route"
  hosts: junos
  gather_facts: false
  tasks:

    - name: "set fact"
      ansible.builtin.set_fact:
        operation: "{{ bypass_or_back }}"

    - name: "get before route"
      import_role: 
        name: show_route
      vars:


    - name: assert res_show
      ansible.builtin.assert:
        that:
          - via_IF == "ge-0/0/0.0"
      when: inventory_hostname in ['VMX01','VMX02']

    # - name: "interface disable"
    #   junipernetworks.junos.junos_config:
    #     lines:
    #     - set interfaces ge-0/0/1 disable

    - name: "change ospf metric"
      junipernetworks.junos.junos_config:
        lines:
        - set protocols ospf area 0.0.0.0 interface ge-0/0/0.0 metric 1
      when: inventory_hostname in ['VMX01','VMX02']

    - name: "get agter route"
      import_role: 
        name: show_route

    - name: assert res_show
      ansible.builtin.assert:
        that:
          - via_IF == "ge-0/0/2.0"
      when: inventory_hostname in ['VMX01','VMX02']
