---
- name: "shutdown ge-0/0/1"
  hosts: junos
  gather_facts: false

  tasks:
    - name: "conf ge-0/0/1"
      junipernetworks.junos.junos_interfaces:
        config:
          - name: ge-0/0/1
            enabled: true

    - name: "pause 10 seconds"
      pause:
        seconds: 10

    - name: "get status ge-0/0/1"
      junipernetworks.junos.junos_command:
        commands: "show interfaces ge-0/0/1 terse"
      register: res_show
      tags:
        - connectivity_check

    - name: "debug res_show"
      ansible.builtin.debug:
        msg: "{{ res_show.stdout_lines[0][1] }}"
