---
- name: "change ospf route"
  hosts: junos
  gather_facts: false
  tasks:
    - name: "before route ospf"
      junipernetworks.junos.junos_command:
        commands: "show route {{ peer_loopback }}"
      # loop: 
      #   - "10.100.100.1/32"
      #   - "10.100.100.2/32"
      register: res_show
      when: inventory_hostname in ['VMX01','VMX02']

    - name: "debug res_show"
      ansible.builtin.debug:
        msg: "{{ res_show.stdout_lines[0] }}"
      when: inventory_hostname in ['VMX01','VMX02']

    # - name: "interface disable"
    #   junipernetworks.junos.junos_config:
    #     lines:
    #     - set interfaces ge-0/0/1 disable

    - name: "change ospf metric"
      junipernetworks.junos.junos_config:
        lines:
        - set protocols ospf area 0.0.0.0 interface ge-0/0/0.0 metric 150
      when: inventory_hostname in ['VMX01','VMX02']

    - name: "after route ospf"
      junipernetworks.junos.junos_command:
        commands: "show route {{ peer_loopback }}"
      # loop: 
      #   - "10.100.100.1/32"
      #   - "10.100.100.2/32"
      register: res_show
      when: inventory_hostname in ['VMX01','VMX02']

    - name: "debug res_show"
      ansible.builtin.debug:
        msg: "{{ res_show.stdout_lines[0] }}"
      when: inventory_hostname in ['VMX01','VMX02']