---
- name: "before ospf route"
  hosts: junos
  gather_facts: false
  tasks:
    - name: "get show route ospf"
      junipernetworks.junos.junos_command:
        commands: "show route protocol ospf"
      register: res_show
      tags:
        - check_route

    - name: "debug res_show"
      ansible.builtin.debug:
        var: res_show
