---
- name: "get route"
  junipernetworks.junos.junos_command:
    commands: "show route {{ peer_loopback }}"
    display: json
  register: res_show  

- name: "define via_if"
  ansible.builtin.set_fact:
    via_if: "{{ res_show.stdout[0]['route-information'][0]['route-table'][0]['rt'][0]['rt-entry'][0]['nh'][0]['via'][0]['data'] }}"

- name: "debug res_show"
  ansible.builtin.debug:
    msg: "{{ via_if }}"

- name: assert res_show
  ansible.builtin.assert:
    that:
      - via_IF == "ge-0/0/0.0"
