---
all:
  children:
    junos:
      hosts:
        vmx01:
          ansible_host: 66.129.234.213
          ansible_port: 34000
      vars:
        ansible_network_os: junipernetworks.junos.junos
        ansible_connection: ansible.netcommon.netconf
        ansible_password: "Juniper!1"
        ansible_user: "jcluser"
