---
all:
  children:
    junos:
      hosts:
        vmx01:
          ansible_host: 66.129.234.213
          ansible_port: 35003
        vmx02:
          ansible_host: 66.129.234.213
          ansible_port: 35006
        vmx03:
          ansible_host: 66.129.234.213
          ansible_port: 35009
        vmx04:
          ansible_host: 66.129.234.213
          ansible_port: 35012
      vars:
        ansible_network_os: junipernetworks.junos.junos
        ansible_connection: ansible.netcommon.netconf
        ansible_password: "Juniper!1"
        ansible_user: "jcluser"
