---
name: test ospf
run-name: ${{ github.actor }} is testing out GitHub Actions
on: [workflow_dispatch]
jobs:
  ansible_in_docker:
    runs-on: ubuntu-latest
    container:
      image: kaiuchida/ansible-execution-env:1.0
      options: --user root
    steps:
      - name: check my ip
        run: curl http://inet-ip.info/

      - name: checkout code
        uses: actions/checkout@v3

      - name: connectivity_check
        uses: corrupt952/retry-command@v1.0.7
        with:
          command: ansible-playbook -i inventory junos_check_ospf.yml --tags "check_route"
          max_attempts: 5
          retry_interval: 5

      - name: ansible ospf
        run: ansible-playbook -i inventory junos_change_ospf.yml